### PR TITLE
Typescript ftw

### PR DESCRIPTION
**Pull request by plhnk**
- add Liferay's eslint config
- add Gatsby's typescript plugin
- fixes for Lexicon

### CODE REVIEW

**Comment by plhnk** [comment]
hey @liferay-design/lexicon — made a few small updates so the homepage is more mobile friendly, don't merge this just yet! Will try to get a few more in so we can close #382.

Let me know if there's anything funky (cards are still too wide on screens < 600px, working on it) — or if there's anything you'd like on the homepage!

**Comment by plhnk** [comment]
okay I think we can close #382 after this is merged — what do you all think? Check [the deploy preview](https://deploy-preview-713--happy-jackson-1b6bb8.netlify.com/lexicon), feedback is much appreciated!

**Comment by victorvalle** [comment]
I would vertically center the clay card. The rest seems to be really good for me.
Thanks @plhnk :)

**Pull request merged**
