### PR TITLE
Update links to internal copyright policies

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by victorvalle** [comment]
@plhnk I've done a cherry pick from David's latest PR but I think I'm doing something wrong sending this PR. Could you check what is happening?

**Comment by plhnk** [comment]
this PR is kind of messy — I think its probably best to close this for now 😅

**Comment by plhnk** [comment]
Screen Shot 2020-02-26 at 7 02 51 AM

sorry for my earlier message (amended), I should have qualified 'messy' 😬 --> there are a lot of "duplicate" commits in your branch. I put "duplicate" in quotation marks, because git doesn't realize they are duplicate because they have unique hashes. 

Once something is merged into the master branch (/liferay-design/liferay.design), there is a unique hash generated --> so every time you have a PR merged, you have to align your branch (/victorvalle/liferay.design) with upstream (/liferay-design/liferay.design). 

This means once your PR is merged, doing `git reset --hard upstream/master` so that your local branch looks exactly the same as what master is (now your commit hashes will be the same as what is upstream).

The above may have some technical inaccuracies, but it is functionally correct :) 

So — please close this one, and I will comment on the other PR what to try

**Comment by victorvalle** [comment]
Thanks @plhnk !

**Pull request closed without merging**
