### PR TITLE
Apply button duplicated at the top of the page

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by plhnk** [comment]
Thanks for the idea @victorvalle!

It does make applying easier, but I'm not sure that is entirely positive :) 

From what I've seen, very few applicants are reading the job description and following the instructions as it is. These are low-quality candidates — IMHO making it easier for LQC do apply, makes it harder for us...what do you think?

**Comment by victorvalle** [comment]
We can try and see if the candidates quality improvement and the amount is significant or not.

**Comment by plhnk** [comment]
is this change intended to increase candidate quality?

**Comment by victorvalle** [comment]
This is intended to not need to read again all the page when one has already read it

**Comment by plhnk** [comment]
@victorvalle I prefer to close this PR and work out in a mockup first, can we move it there?

**Comment by victorvalle** [comment]
I thought you told me this in person rather than through git. I'm getting old.
I'm ok and sad at same time

**Pull request closed without merging**
