### PR TITLE
Hotkey post / Improve tags

### PR DESCRIPTION
**Pull request by plhnk**
- DBP post on keyboard shortcuts
- make tags look a little better across the site
- update [tags](https://liferay.design/tags) page

### CODE REVIEW

**Comment by plhnk** [comment]
@victorvalle more thoughts? i guess i should have broken this PR into a couple different ones...

**Comment by victorvalle** [comment]
I feel the article must reflect that hotkeys depend on language and how some companies bet on that instead of a unique hotkey or a hotkey standard.

**Comment by victorvalle** [comment]
Good update on the article, simple and clean!

**Comment by victorvalle** [comment]
Thanks Paul! I like when you write these wonderful articles :)

**Pull request merged**
