### PR TITLE
LEXI-827: Update Header Component

### PR DESCRIPTION
**Pull request by drakonux**
See https://issues.liferay.com/browse/LEXI-827

### CODE REVIEW

**Comment by victorvalle** [comment]
@plhnk I've tried to discard 3cdbce8 to continue working. In my PR you can see that, but I'm not sure about merging what I did

**Comment by plhnk** [comment]
If I'm understanding @victorvalle, it sounds like you want to make a few changes to what @drakonux has done in his PR? Specifically you want to amend changes in https://github.com/liferay-design/liferay.design/commit/3cdbce837b216a5c8008407446f514f2df7cae84?

I'm not super fluent in git, I think this is a difficult task, so I will say what I _think_ the process would be, which you could verify with maybe Marcos or Edu...and then I will say what I would do as an easier (IMHO --> but probably not if you're more savvy) option.

## My understanding of the "correct" process
1. You set your local environment to the same as David's — meaning you need to set his repo [as a remote](https://help.github.com/en/github/using-git/adding-a-remote) (I'm going to use his username in the sample commands)
    1. `git remote add drakonux https://github.com/drakonux/liferay.design`
    1. verify it has set correctly by running `git remote -v` — you should see 
    ``` sh
    drakonux https://github.com/drakonux/liferay.design.git (fetch)
    drakonux https://github.com/drakonux/liferay.design.git (push)
    ```
    1. how that you have his repo set as a remote, you need to set your local even with his: `git reset --hard drakonux/LEXI-827`
    1. if you hadn't already, now its probably a good idea to create a local branch (`git branch checkout -b LEXI-827`)
1. Now, you make your changes, committing along the way
1. Once you have finished, you send a PR to David's repo
1. He merges the changes into his branch (LEXI-827) — which (I think) should populate them here in this PR
1. finis

Now, the above should be verified by someone smarter than me...I can't guarantee it will work.

## What I would do
1. Merge this PR
1. Reset your environment even with master (`git reset --hard upstream/master`)
1. Make your changes
1. Send a new PR

:D

**Comment by plhnk** [comment]
Okay so based on #693 it sounds like you are wanting to only remove @drakonux's last commit (3cdbce8) from this pull? 

I would suggest then that he does this only on his side, it will be much more complicated for you to be involved :)

## Steps for @drakonux 
1. `git reset --hard 869d5c6`
1. `git push origin/LEXI-827 --force`

This essentially removes the commit from this pull (at least it should).

**Comment by victorvalle** [comment]
Closing this on favor of a fix that removed the last commit

**Pull request closed without merging**
