### PR TITLE
Satellite doc  updates

### PR DESCRIPTION
**Pull request by victorvalle**
Added product menu updates
Added Global menu page

### CODE REVIEW

**Comment by victorvalle** [comment]
Does the last commit looks ok @plhnk ? It is a merge due to a master update.

**Comment by plhnk** [comment]
It looks like the last should be removed... I will spend some time today to clean up the branches/open PRs so we don't have so many open :) then check back — the merge commit shouldn't be necessary

**Comment by victorvalle** [comment]
should I remove this last commit? I actually don't know if you are still doing things

**Comment by plhnk** [comment]
yes go ahead and remove it — I will wait before opening any other PRs

**Pull request merged**
