### PR TITLE
Add Form Sheet section to Lexicon/Patterns

### PR DESCRIPTION
**Pull request by hold-shift**
I've updated Lexicon's site as requested in https://issues.liferay.com/browse/LEXI-1032

Please, check this out before publishing.

### CODE REVIEW

**Comment by victorvalle** [comment]
@hold-shift please add examples and place the page inside Forms section as the first entry

**Comment by victorvalle** [comment]
Help @plhnk :) pleeeeease

**Comment by plhnk** [comment]
I think.... it's better for @hold-shift to do a hard reset at 1675162 — and then cherry pick 8146457 into the branch...then force-push to his branch.

Basically we want to cut out any merge commits — that's where the conflicts typically happen:
- efe5596
- 015d916

let me know if that makes sense, I can also do a screenshare if that helps

**Comment by hold-shift** [comment]
Ok, I've discarded this branch and created a new one to avoid conflicts. Thanks guys!

Continues on .. https://github.com/liferay-design/liferay.design/pull/833

**Comment by plhnk** [comment]
thanks @hold-shift !

**Pull request closed without merging**
