### PR TITLE
Modal buttons at footer description correction

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by plhnk** [comment]
fix for #572

**Comment by victorvalle** [comment]
We can already merge this. Are we waiting for something @plhnk ?

**Comment by drakonux** [comment]
🤔But as I said, the changes are different in the descriptions, aren't they? @victorvalle @plhnk

**Comment by plhnk** [comment]
@jonmwood any thoughts?

**Comment by jonmwood** [comment]
Yeah as @drakonux said the modal.md file is correct where it says "When a modal has a footer, place the actions inside and align them to the **right**. Follow this order for your actions:"

Whereas modal.mdx still says **left** which is incorrect. So we just need to update the mdx file.

@victorvalle @plhnk

**Comment by plhnk** [comment]
thanks @jonmwood — @victorvalle is out on PTO this week, so we'll have to wait until he gets back, will let him make the updates to his PR :)

**Comment by victorvalle** [comment]
I've sent and merged the change in the correct file in https://github.com/liferay-design/liferay.design/pull/577

**Pull request closed without merging**
