### PR TITLE
Optimize article imges

### PR DESCRIPTION
**Pull request by carolrodmar**
Uploading again some images for last articles

### CODE REVIEW

**Comment by plhnk** [comment]
Can you double-check this @carolrodmar ? it looks like almost all of the images are actually larger in filesize than they were before...unless I'm reading it wrong? 

I'd suggest moving the images into the article folder in the `src` (see @MiriamManso's [article on contingency tables](https://github.com/liferay-design/liferay.design/tree/master/src/markdown/articles/2021/using-contigency-tables)) — this will allow you to keep full-size images in the repo, but Gatsby will actually do the heavy lifting of optimizing them at the build.

**Comment by carolrodmar** [comment]
Thanks! @plhnk I will check this!

**Comment by carolrodmar** [comment]
Made a new commit with the images located in the article folder @plhnk

**Review by plhnk — APPROVED** [review]
thanks @carolrodmar, great work!

**Pull request merged**
