### PR TITLE
Sidebar for dark theme to be another light color

### PR DESCRIPTION
**Pull request by victorvalle**
This is something for you to consider.
The black mass on the left side really drains all my attention. This is just an improvement that would solve my problem.

### CODE REVIEW

**Comment by plhnk** [comment]
🤔

**Comment by plhnk** [comment]
how it started:
image

how it's going:
image

This does not get my vote, I'm sorry. 

If you don't prefer the dark theme — that's fine, in my mental backlog there is a [theme switcher](https://paul.hanaoka.co) that I want to do, so if you want to make a ticket and move it, we can make that happen.

**Comment by victorvalle** [comment]
should we have the sidebar in the handbooks' landing page? we don't have it in Lexicon. That would solve the landing issue. And then my changes are nice for interior pages :)

**Comment by plhnk** [comment]
that's funny, I was thinking that we should do the opposite....move the sidebar to the Lexicon homepage...it makes finding information a lot easier 😬 

(BTW this was @ryconn888 's idea for the handbook, I can't take the credit)

**Pull request closed without merging**
