### PR TITLE
Images change for charts

### PR DESCRIPTION
**Pull request by victorvalle**
@drakonux @hold-shift I've changed all images.
I've exported them as PNGs this time as it reduces much more the weight.

I haven't change the font from Open Sans to San Francisco, I don't know if we want to do that change too.

Please review and let me know.

### CODE REVIEW

**Comment by hold-shift** [comment]
Hi @victorvalle. They look a bit blurry on my computer, but this is something that was already happening before this change. Maybe this will be fixed when we jump directly to @ 2x or higher version of the images

**Comment by hold-shift** [comment]
Sorry, I didn't see it right, the page's search engine redirected me to the site and I didn't realize it. They look perfect, even on the macbook screen.

**Comment by plhnk** [comment]
good to merge? or should I generate a deploy preview?

**Comment by victorvalle** [comment]
I think so @plhnk

**Pull request merged**
