### PR TITLE
Gestalt Principle Article

### PR DESCRIPTION
**Pull request by MiriamManso**

### CODE REVIEW

**Comment by victorvalle** [comment]
@plhnk could you review this? the images do not have high quality, we tried to reduce the weight and then we lost quality on the process :(
I don't know what can we do to improve on the images.

**Comment by plhnk** [comment]
@victorvalle for the time being, (until we can solve #389) we have to be okay w/larger images (or poorer quality images). Up to you guys!

**Comment by plhnk** [comment]
Or if you like @MiriamManso — you can nuke this pull-request and try adding your article in the CMS. I just sent you an invitation, you should be able to copy/paste your markdown — the one annoyance would be redoing all of your images....let me know if you want to try that route!

**Comment by victorvalle** [comment]
We can close this PR. I've sent the changes in https://github.com/liferay-design/liferay.design/pull/487

**Pull request closed without merging**
