### PR TITLE
Common content patterns

### PR DESCRIPTION
**Pull request by victorvalle**
There is something I need help with. I've tried to put to images in parallel following `smallCards` as usual. But this time it didn't work on my end.

```
<Grid variant='smallCards' >
    <Box>
        <div class="image-container">
            <img
                src="./images/common-content-pattern-19.jpg"
            />
        </div>
        <p class="do">Do</p>
    </Box>
    <Box>
        <div class="image-container">
            <img
                src="./images/common-content-pattern-20.jpg"
            />
            </div>
        <p class="dont">Don't</p>
    </Box>
</Grid>
```

Images in this PR are compressed with tinyImage compressor plugin in Figma. But I don't think that is the issue. I'm a bit lost as I was working on this page all week and everything was working out well.

### CODE REVIEW

**Comment by victorvalle** [comment]
I've done a test placing an image in static/images/lexicon instead of next to the page and it works well.

image


It seems there is something to be improved in the image processor/method/whatever it is called :)

**Comment by plhnk** [comment]
Gatsby only processes images referenced in the markdown syntax `image` — any images referenced by components will need to, as you discovered, still be referenced in the static folder...

There is a way to query them, I think, however I have not looked into this very much.

**Comment by victorvalle** [comment]
I see. 

If we don't have that way of querying them, we will opt to have all our images in `static/images/lexicon`. At least for the moment, we will continue working that way.

**Comment by plhnk** [comment]
Why not just have the markdown images in `src` so they can be optimized — and then any inline images (referenced in HTML) put in static?

Its a little bit of work, but its definitely worth the improvements. Especially since inline images aren't as common.

**Review by plhnk — APPROVED** [review]

**Pull request merged**
