### PR TITLE
Adding a brief Lexicon introduction to handbook

### PR DESCRIPTION
**Pull request by fapires**
Just added a brief description of Lexicon and some important information to make it easier for onboarding new hires.

### CODE REVIEW

**Comment by victorvalle** [comment]
@drakonux and @laugardie should review this :)
I see that some data could be outdated. Like the last presentation in the page.
Also, a thing to fix is removing Clay link in the heading.

**Comment by drakonux** [comment]
Hi Felipe, 

I agree with Victor. The last presentation is outdated (Clay & Lexicon). I recommend to remove it and leave the first one about workflows because it's more updated with the new way to work together.

Besides, the rest of the content seems correct. Thanks for doing that.

ps. We should create a new presentation with the Front-End-Infrastructure team. I take note and I will talk with Chema to generate a new one.

**Comment by fapires** [comment]
Thanks @victorvalle and @drakonux. Just fixed that.

**Comment by fapires** [comment]
@plhnk I would like to have it added to the Handbook till Friday. Do you think it's possible?

**Comment by plhnk** [comment]
@fapires you want me to wait until Friday to merge? Or you want it merged before Friday?

**Comment by fapires** [comment]
Before Friday! :)

**Pull request merged**
