### PR TITLE
Allow LexiconCard to have horizontal and vertical orientation and apply to home page

### PR DESCRIPTION
**Pull request by protoEvangelion**

### CODE REVIEW

**Comment by plhnk** [comment]
@protoEvangelion even tho I resolved the conflicts ([commit](https://github.com/liferay-design/liferay.design/pull/143/commits/dba22b1a65de9f67958029f0d354527b24367a2e)) it's still saying it cannot be rebased and merged — what am I doing wrong here?

**Comment by protoEvangelion** [comment]
sometimes the commits get out of sync
try to back up dev to another branch
create a fresh branch from master (make sure its up to date on your local)
then try to use a visual tool like GitKraken to just pick the new commits and place them on top of master.

**Comment by plhnk** [comment]
@jamesjlyons he mentioned your favorite tool...can you help out? 😁

**Comment by plhnk** [comment]
hey @phillipchan2 — thanks for doing this, and for the patience — is there any way you could try to reset your local repo w/what we currently have upstream and try this pull again? I think the diffs between your origin and our upstream are causing some commit history issues...is there a better way to fix this?

**Comment by phillipchan2** [comment]
@plhnk do you still need this?

**Comment by plhnk** [comment]
@phillipchan2 I mean... "need" is a strong word. I need oxygen and food. This would be great to have, and if you can make the time for this that would be really appreciated, but nobody's gonna die if this doesn't get done.

**Comment by phillipchan2** [comment]
@plhnk  should hopefully fix it https://github.com/protoEvangelion/liferay.design/pull/9

**Comment by plhnk** [comment]
thanks @phillipchan2 !

**Pull request closed without merging**
