### PR TITLE
Broken feeling fix

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by plhnk** [comment]
I will leave this up to @ryconn888 to review — he designed the 'we're hiring' banner to be cut off in alignment to the grid on the right side (hence the psuedo element w/black bg) — here's the preview: https://deploy-preview-386--happy-jackson-1b6bb8.netlify.com

**Comment by victorvalle** [comment]
👍 :S

**Comment by ryconn888** [comment]
Yep, @victorvalle this is intentional -- we should leave it

**Comment by plhnk** [comment]
thanks for weighing in @ryconn888 — @victorvalle leaving this for you to review, if you have any additional remarks, thoughts, etc — otherwise please close at your convenience :)

**Pull request closed without merging**
