### PR TITLE
add figma resources and simplify landing page grid template

### PR DESCRIPTION
**Pull request by abelhancock**

### CODE REVIEW

**Comment by plhnk** [comment]
how could we have "all figma resources" link to something that has all the figma resources from our team? instead of a single designer's profile page? 😬

**Comment by victorvalle** [comment]
Related to this, we would like to post an update of Lexicon Figma Library. How do we do that?

**Comment by plhnk** [comment]
@victorvalle what do you have in mind?

**Comment by abelhancock** [comment]
@plhnk I think that'd be ideal! The two resources on our team profile are already linked on this page so there aren't really more yet... unless you're thinking to link to the open source project. But it'd probably be better to do it all through community now we can! Any suggestions??

**Comment by plhnk** [comment]
@abelhancock what do you think about a page at `/resources/figma/designers` — it would have cards for all the designers who have put their Figma community links in `authors.yaml`?

**Comment by abelhancock** [comment]
@plhnk I like that idea! Only downside could be lots of clicking different profiles to discover content. Would it be easy enough to create a page with cards that link directly to each resource individually? Or is that too much to maintain another collection of content?

**Review by plhnk — COMMENTED** [review]
nooooo! you gave up `@abel`??

**Comment by plhnk** [comment]
thanks @abelhancock great update!

**Pull request merged**
