### PR TITLE
Twitter Cards for Articles

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by victorvalle** [comment]
@plhnk i've tested twitter cards from Lexicon with the preview url here and it works https://cards-dev.twitter.com/validator
I think it will work too for the article posts.
I will do the same for events soon

**Comment by plhnk** [comment]
awesome — will you add those commits to this PR?

**Comment by victorvalle** [comment]
yes :)

**Comment by victorvalle** [comment]
I had issues working on events. The author and featured image are null when trying to read shape the header :(

**Pull request merged**
