### PR TITLE
Card images

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Review by plhnk — COMMENTED** [review]
if you're going to all this trouble to update the images, why not put them into the new image paradigm? :D

**Comment by victorvalle** [comment]
Because the method facilitated doesn't work in cases like this:

Screenshot 2021-02-12 at 08 57 47

and we have many :)

**Comment by plhnk** [comment]
You mean in the DoDont component? Or just 50/50? 

Check the foundations/grid page, maybe that can help. There's a way to style.

**Comment by victorvalle** [comment]
I know that, but it isn't what we are looking for. We need the styles. Something like this where the images work well as when they are processed in static folder

```
<Grid variant='smallCards' >
	<Box>
		<div class="image-container">
			<img
			/>
		</div>
		<p class="do">Do</p>
	</Box>
	<Box>
		<div class="image-container">
			<img
			/>
			</div>
		<p class="dont">Don't</p>
	</Box>
</Grid>
```

**Comment by plhnk** [comment]
I'm confused — in this page all the images are being referenced in basic markdown syntax?

**Comment by victorvalle** [comment]
For cards, there are not do's and don'ts but several pages have that. Do you expect us to only do it for those images that are under "do and don't" (2 columns)?

**Comment by plhnk** [comment]
Yeah IMHO better to at least have the images that can be optimized, optimized.

And gradually we can fix the others.

Easier to do it incrementally, better for everyone to start building the new habits.

**Comment by victorvalle** [comment]
Ok, we will do so

**Comment by victorvalle** [comment]
Done

**Pull request merged**
