### PR TITLE
make images expandable

### PR DESCRIPTION
**Pull request by abelhancock**
- [ ] Resolve error with margin (something related with the const alignments on state toggle)
- [x] Figure out why transitions aren't working
- [x] Just generally have @plhnk clean things up
- [x] Add option to close modal with esc key

### CODE REVIEW

**Comment by plhnk** [comment]
The margin error is... ignorable. I probably shouldn't have written it that way, basically I have the alignments set by changing the left and right margins — but also have a prop that lets you set all margins (shorthand). To fix this error, we'd have to refactor to take the shorthand and convert it into individual properties...which doesn't seem worth it right now since its only a console error at this point...

**Comment by plhnk** [comment]
[transitions don't work when the display property is changed](https://stackoverflow.com/questions/5951200/css-transitions-not-working)

**Comment by abelhancock** [comment]
ohhhh I didn't know (or forgot) that changing display causes all transitions not to work. Lots of options to fix that then 👌

For the margin error, did you notice that after opening/expanding the image the inline image becomes left (or right) aligned with the text? Still very minor but don't know if you saw that.

**Review by plhnk — COMMENTED** [review]
great work, thanks Abel

**Comment by abelhancock** [comment]
ah 💩 ........

**Comment by plhnk** [comment]
what....just happened

**Comment by abelhancock** [comment]
I think the technical term is "self-sabotage"

**Pull request closed without merging**
