### PR TITLE
Update stickers.mdx

### PR DESCRIPTION
**Pull request by MarkusHmr**
Changed the description part and removed some stickers where we (Emily & Myself)decided they are not useful anymore.

### CODE REVIEW

**Comment by victorvalle** [comment]
Why is important to name the vendor @MarkusHmr and @emilyyoung ?

**Comment by MarkusHmr** [comment]
Hi @victorvalle ,
because new Marketeers might not know where to order and with sticker mule we had the best results in printing quality.
So we encourage with that everyone order at sticker mule. ;)

**Comment by victorvalle** [comment]
Thanks @MarkusHmr !

**Comment by MarkusHmr** [comment]
Thank you @victorvalle !! 
This was my first pull request! 👯

**Comment by victorvalle** [comment]
I wanted to make you suffer a bit :P 

We are expecting more PRs :)

**Pull request merged**
