### PR TITLE
Create, update, and fix designer profiles

### PR DESCRIPTION
**Pull request by nhisamoto**
Fixing broken design profiles
Updating existing design profiles
Creating new design profiles

### CODE REVIEW

**Comment by plhnk** [comment]
thanks @nhisamoto — it looks like there's some old commits in this PR, can you remove them? everything before [30c136f](https://github.com/liferay-design/liferay.design/pull/1117/commits/30c136f2829da5d6d5d878d07650abb5b36c692e) is old and will trigger merge conflicts

**Comment by nhisamoto** [comment]
@plhnk Is there a best way to accomplish this?
I researched a bit. I wasn't sure if cherry-picking was the best way to accomplish this but the instructions for this application was not clear for me.

**Comment by nhisamoto** [comment]
@plhnk I did the steps above.
Let me know if that resolved the issue.

**Comment by plhnk** [comment]
@nhisamoto 🐐 status — running deploy preview, then will merge!

**Comment by plhnk** [comment]
@nhisamoto thanks so much for all the work in your PR — [deploy preview failed](https://app.netlify.com/sites/happy-jackson-1b6bb8/deploys/62f14beb79167a140f548bf2), looks like it was Temistocles' [2nd behance link](https://github.com/liferay-design/liferay.design/pull/1117/commits/01abcd9c5a31b42907a4a6b7030c883a85e10d26#diff-a67cea40bf610afe3bde2e1031a2eb3bf189c0f616fab1c35b43eeb27cea623f) that broke it

we have two options:
1. easiest (2 min of work) — remove one of the behance lines from his entry in authors.yaml
2. slightly trickier (~30 min of work? unknown) — add functionality so that we can add multiple behance accounts 

_there's also the possibility that one of those links isn't actually for behance and its for another app... so want to double-check that as well_ 

Let me know what you want to do! I'm happy to help figure out #2 if that's the route you want to go.

**Comment by nhisamoto** [comment]
@plhnk I went with option #1 for now to get the new hire profiles live and we can introduce them on Slack.
I will address #2 another time and would love any help/tips.

**Comment by nhisamoto** [comment]
@plhnk I removed the accents from Temistocles' file names

**Pull request merged**
