### PR TITLE
Fix accessibility issues created by unnecessarily restricting scroll events

### PR DESCRIPTION
**Pull request by plhnk**
Because I am a very smart person™️ I thought it would be a great idea to hide everything that was outside of the horizontal viewport at the `body` selector level. 

Turns out, this is not a good idea — which, had I thought about it for more than a second, I would have realized. Because, when you do something like this at such a high level, you cannot possibly forsee the situations when...you actually would not want this in a lower level template or component. 

So, the lesson here is — take the time to write clean code in the first place, if something is giving you horizontal scroll and you don't want it, then fix it at that level...don't go so high up in the tree.

This should solve #660 — it will probably create more issues, so as you see them, please report. I've already fixed one in the Articles template.

### CODE REVIEW

**Comment by plhnk** [comment]
@chrberndt and @jacobcerda please check out [the deploy preview](https://5ea91e18e972260006b613cf--happy-jackson-1b6bb8.netlify.app/lexicon) and let me know if this solves #660 — thanks!

**Comment by plhnk** [comment]
cc @victorvalle @drakonux

**Comment by victorvalle** [comment]
Hi @plhnk !
I believe one of these changes introduces the following bug

image

A dark stripe after the main article image.

**Comment by plhnk** [comment]
ahhh thanks @victorvalle — I didn't check that in the preview...looks fine in my local, but yes I see that now... sending a fix

**Comment by jacobcerda** [comment]
@plhnk There's still no scrollbar but I am able to scroll using arrow keys now! :+1:

**Pull request merged**
