### PR TITLE
Add missing profile icons

### PR DESCRIPTION
**Pull request by nhisamoto**
Icons for Pedro, Temistocles, Leo, and Naoki were missing.
Added font-awesome icons after proper naming.

### CODE REVIEW

**Comment by plhnk** [comment]
Thanks @nhisamoto ! on a rolll....icons are a little tricky, adding them is half the battle — the other half is using our icon utility script so they get added to our svg sprite.

To do this, type `npm run icons` into the console in the root directory.

This may be complicated if you don't have it running on your machine locally, lmk and I can do it quickly and add to your PR so this doesn't sit open for awhile.

**Comment by nhisamoto** [comment]
Hey @plhnk !
If you would be able to take care of the icons for this round, that'd be great!

**Comment by plhnk** [comment]
@nhisamoto — [merging this should do it!](https://github.com/nhisamoto/liferay.design/pull/1)

**Comment by nhisamoto** [comment]
@plhnk 🐐 Merged!

**Comment by plhnk** [comment]
okay [last...one](https://github.com/nhisamoto/liferay.design/pull/2) 🥲

**Comment by nhisamoto** [comment]
@plhnk Thank you! **Rebase and merged!**

**Pull request merged**
