### PR TITLE
Writing framework

### PR DESCRIPTION
**Pull request by victorvalle**

### CODE REVIEW

**Comment by victorvalle** [comment]
Please don't merge it. We have a pending change.

**Comment by plhnk** [comment]
@victorvalle what do you think about moving `Writing` to its own subsection? IMHO it's starting to get a little deep, and due to the significance i think it would be good to surface above

thoughts?

cc @cj213x @ryconn888 @susanavr @fapires

**Comment by victorvalle** [comment]
I think it would be positive

**Comment by plhnk** [comment]
what needs to happen for this to be mergeable? would like to get it in there since its almost 3 weeks open....stale PRs create merge conflicts...

**Comment by victorvalle** [comment]
This can be merged now @plhnk

**Comment by victorvalle** [comment]
Changes done @plhnk ! Sorry for our delay :)

**Pull request merged**
