### PR TITLE
Stickers page with several stickers

### PR DESCRIPTION
**Pull request by victorvalle**
@plhnk I've created the stickers page.
As you can see, I've modified a bit the ImageDownload component because I'm linking to the document in Dropbox to reduce the weight on our side. Good and bad because they can then navigate Dropbox.

@MarkusHmr I've plotted in the screen only the ones that are ready to print and that are shared as individual stickers. At the end of the page, I also share a catalog pdf with more. But it would be nice if any comm designer could provide the individual stickers in the ready to print folder, so I can expose all of them.

Good and bad:
* Good: we have many stickers
* Bad: we have many old ones that we may want to hide as they are outdated

Screen-Recording-2020-02-28-at-1

cc: @emilyyoung

### CODE REVIEW

**Comment by victorvalle** [comment]
I would like to bring our stickers to this page too:
- liferay.design
- Liferay design logo

**Comment by victorvalle** [comment]
You are right :P. I wanted to do something cleaner. But I ended up doing this. I tried yours in a different way that didn't work to me.

**Comment by MarkusHmr** [comment]
Hey Guys,
Can we make this live? :)

**Comment by plhnk** [comment]
Thx for the followup/reminders @MarkusHmr and @drakonux :) 

There's a couple issues that we should resolve before publishing:
1. Please double-check this in [the deploy preview](https://deploy-preview-697--happy-jackson-1b6bb8.netlify.com/blueprints/resources/stickers), but for me all of the download links are broken — can someone else verify? If these links are broken, we should move these assets to a more stable location, my suggestion would be in the appropriate [resources folder in Drive](https://drive.google.com/open?id=155mnDbxmQNzkG9jz7kiOT4BTFVIK4ov6).
1. Currently the [catalog link](https://deploy-preview-697--happy-jackson-1b6bb8.netlify.com/blueprints/resources/stickers/#catalog) goes to a [410](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) — as with above, I suggest we put production-ready files in a more stable location.
1. I would like to fix the issue [I brought up earlier](https://github.com/liferay-design/liferay.design/pull/697#pullrequestreview-366531955), I can get to that some night this week and send a PR to @victorvalle's branch
1. [It sounds like the content on the page isn't set](https://github.com/liferay-design/liferay.design/issues/691#issuecomment-593287896) — would be good to have a list of the ones that we want on there, and maybe some groups as well so it can be a collapsable like we have on [other pages](https://liferay.design/blueprints/resources/product-screens/).

**Comment by victorvalle** [comment]
Hi!
1. I'm ok with this if d-comm wants to make that movement. (@MarkusHmr )
2. Maybe there was a pdf modification and re-upload. This could change the url.
3. Ok.
4. I like the idea of groupings. I thought years could be a nice option so we know the time they have.

**Comment by victorvalle** [comment]
@MarkusHmr @emilyyoung if you guys could find some time to put the stickers in a folder in drive it would be perfect.
When that is done we will modify this PR and merge it :)

**Comment by MarkusHmr** [comment]
Hi @victorvalle 
you can find all the print files for the stickers here:
[HERE](https://drive.google.com/open?id=1evcTUDDF2J96n-4528Cy3a7eo3PgjpHG)

**Comment by victorvalle** [comment]
@plhnk this should be now ready to publish

Thanks @MarkusHmr for the links and the images :)

**Comment by victorvalle** [comment]
Should we put liferay design stickers here too?

**Comment by victorvalle** [comment]
Getting sad with no merging this :( @plhnk

**Comment by plhnk** [comment]
hey @victorvalle — sorry to be an aguafiestas, I checked it out and I see your updated links and images, thanks for doing all that! I think we're still [waiting on a few things](https://github.com/liferay-design/liferay.design/pull/697#issuecomment-614118873) — hoping @MarkusHmr can weigh in...

Unless I missed it — I looked very quickly, and at the least the catalog issue is still pending. Once the content stuff comes through and is more or less finalized, I'll fix the <Link> component and merge.

**Comment by victorvalle** [comment]
If you mean the document with all stickers. That doesn't exist now. I don't think it makes sense to have it as we would have to update the url each time. I removed it in my last PR.

Even we can go ahead without that and if they want to provide later on, we just add it

**Comment by victorvalle** [comment]
@plhnk reviewed and updated

**Comment by MarkusHmr** [comment]
Hey @plhnk & @victorvalle ,
do you need anything from me? I'm happy to contibute.

**Pull request merged**
