### PR TITLE
google-sheets

### PR DESCRIPTION
**Pull request by protoEvangelion**
Hey @plhnk lets talk about how this works. You won't be able to run `npm run dev` it unless you have proper credentials.

### CODE REVIEW

**Comment by plhnk** [comment]
Wow amazing — I'm in a training from 8-2, but free before/after!

Also — I forgot to tell you we updated our workflow...we're using the branches correctly now, so all work gets done on Master, then we push to Dev (which updates [dev.liferay.design](https://dev.liferay.design)), then if its all good push to production 😁

**Comment by protoEvangelion** [comment]
O ok the Readme still says send PRs against dev branch. We shouldn't push this to production. Still have quite a few things to iron out.

**Comment by protoEvangelion** [comment]
I am WFH today but will be in tomorrow. We can jump on a call today if you would like though. Tomorrow will be pretty busy.

**Comment by plhnk** [comment]
Okay, whichever you prefer, just ping me! I'm available rest of the day

**Pull request merged**
